# 1. Importando Bibliotecas
Primeiramente, vamos importar as bibliotecas necessárias para nossa análise.

In [1]:

import pandas as pd
import numpy as np

# Definir o formato de exibição de floats para usar vírgula como separador decimal
pd.options.display.float_format = lambda x: f'{x:.3f}'.replace('.', ',')

# visualizacao de dados
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# 2. Carregando o Conjunto de Dados
Usaremos o conjunto de dados "BASE DE DADOS PEDE 2024 - DATATHON.xlsx", que contém características dos alunos da "PASSOS MÁGICOS".

In [2]:

# carregar as abas específicas do arquivo Excel, usando vírgula como separador decimal
df_passos_2020 = pd.read_excel('https://raw.githubusercontent.com/MonicaFMK/FIAP-FASE5/main/BASE%20DE%20DADOS%20PEDE%202024%20-%20DATATHON.xlsx', sheet_name='PEDE2020', decimal=',')
df_passos_2021 = pd.read_excel('https://raw.githubusercontent.com/MonicaFMK/FIAP-FASE5/main/BASE%20DE%20DADOS%20PEDE%202024%20-%20DATATHON.xlsx', sheet_name='PEDE2021', decimal=',')
df_passos_2022 = pd.read_excel('https://raw.githubusercontent.com/MonicaFMK/FIAP-FASE5/main/BASE%20DE%20DADOS%20PEDE%202024%20-%20DATATHON.xlsx', sheet_name='PEDE2022', decimal=',')
df_passos_2023 = pd.read_excel('https://raw.githubusercontent.com/MonicaFMK/FIAP-FASE5/main/BASE%20DE%20DADOS%20PEDE%202024%20-%20DATATHON.xlsx', sheet_name='PEDE2023', decimal=',')
df_passos_2024 = pd.read_excel('https://raw.githubusercontent.com/MonicaFMK/FIAP-FASE5/main/BASE%20DE%20DADOS%20PEDE%202024%20-%20DATATHON.xlsx', sheet_name='PEDE2024', decimal=',')

# 3. Análise Exploratória de Dados
Vamos dar uma olhada nas primeiras linhas do conjunto de dados e entender suas características.

In [3]:
# Tamanho dataset
print(f'Tamanho do nosso Dataset: {df_passos_2020.shape}')
print(f'Tamanho do nosso Dataset: {df_passos_2021.shape}')
print(f'Tamanho do nosso Dataset: {df_passos_2022.shape}')
print(f'Tamanho do nosso Dataset: {df_passos_2023.shape}')
print(f'Tamanho do nosso Dataset: {df_passos_2024.shape}')

Tamanho do nosso Dataset: (1349, 19)
Tamanho do nosso Dataset: (1349, 22)
Tamanho do nosso Dataset: (860, 42)
Tamanho do nosso Dataset: (1014, 48)
Tamanho do nosso Dataset: (1156, 50)

In [4]:
# Verificar nulos
print(f'Quantidade de dados nulos: {df_passos_2020.isnull().sum().sum()}')
print(f'Quantidade de dados nulos: {df_passos_2021.isnull().sum().sum()}')
print(f'Quantidade de dados nulos: {df_passos_2022.isnull().sum().sum()}')
print(f'Quantidade de dados nulos: {df_passos_2023.isnull().sum().sum()}')
print(f'Quantidade de dados nulos: {df_passos_2024.isnull().sum().sum()}')

Quantidade de dados nulos: 11229
Quantidade de dados nulos: 13881
Quantidade de dados nulos: 2956
Quantidade de dados nulos: 21157
Quantidade de dados nulos: 21929

In [5]:
# Verificar duplicidades no df_passos_2020
duplicatas_2020 = df_passos_2020.duplicated().sum()
print(f'Número de linhas duplicadas em df_passos_2020: {duplicatas_2020}')

# Verificar duplicidades no df_passos_2021
duplicatas_2021 = df_passos_2021.duplicated().sum()
print(f'Número de linhas duplicadas em df_passos_2021: {duplicatas_2021}')

# Verificar duplicidades no df_passos_2022
duplicatas_2022 = df_passos_2022.duplicated().sum()
print(f'Número de linhas duplicadas em df_passos_2022: {duplicatas_2022}')

# Verificar duplicidades no df_passos_2023
duplicatas_2023 = df_passos_2023.duplicated().sum()
print(f'Número de linhas duplicadas em df_passos_2023: {duplicatas_2023}')

# Verificar duplicidades no df_passos_2024
duplicatas_2024 = df_passos_2024.duplicated().sum()
print(f'Número de linhas duplicadas em df_passos_2024: {duplicatas_2024}')

Número de linhas duplicadas em df_passos_2020: 0
Número de linhas duplicadas em df_passos_2021: 0
Número de linhas duplicadas em df_passos_2022: 0
Número de linhas duplicadas em df_passos_2023: 0
Número de linhas duplicadas em df_passos_2024: 0

In [6]:
# Informação sobre a base
df_passos_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1349 entries, 0 to 1348
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   INSTITUICAO_ENSINO_ALUNO_2020  728 non-null    object
 1   NOME                           1349 non-null   object
 2   IDADE_ALUNO_2020               728 non-null    object
 3   ANOS_PM_2020                   728 non-null    object
 4   FASE_TURMA_2020                728 non-null    object
 5   PONTO_VIRADA_2020              702 non-null    object
 6   INDE_2020                      728 non-null    object
 7   INDE_CONCEITO_2020             728 non-null    object
 8   PEDRA_2020                     728 non-null    object
 9   DESTAQUE_IEG_2020              728 non-null    object
 10  DESTAQUE_IDA_2020              728 non-null    object
 11  DESTAQUE_IPV_2020              703 non-null    object
 12  IAA_2020                       728 non-null    object
 13  IEG_2020                       728 non-null    object
 14  IPS_2020                       728 non-null    object
 15  IDA_2020                       728 non-null    object
 16  IPP_2020                       728 non-null    object
 17  IPV_2020                       728 non-null    object
 18  IAN_2020                       728 non-null    object
dtypes: object(19)
memory usage: 200.4+ KB

In [7]:
# Informação sobre a base
df_passos_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1349 entries, 0 to 1348
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   INSTITUICAO_ENSINO_ALUNO_2020  728 non-null    object
 1   NOME                           1349 non-null   object
 2   FASE_2021                      686 non-null    float64
 3   TURMA_2021                     686 non-null    object
 4   INSTITUICAO_ENSINO_ALUNO_2021  686 non-null    object
 5   SINALIZADOR_INGRESSANTE_2021   686 non-null    object
 6   PEDRA_2021                     686 non-null    object
 7   INDE_2021                      686 non-null    object
 8   IAA_2021                       686 non-null    object
 9   IEG_2021                       686 non-null    object
 10  IPS_2021                       686 non-null    object
 11  IDA_2021                       686 non-null    object
 12  IPP_2021                       686 non-null    object
 13  REC_EQUIPE_1_2021              686 non-null    object
 14  REC_EQUIPE_2_2021              686 non-null    object
 15  REC_EQUIPE_3_2021              686 non-null    object
 16  REC_EQUIPE_4_2021              686 non-null    object
 17  PONTO_VIRADA_2021              686 non-null    object
 18  IPV_2021                       686 non-null    object
 19  IAN_2021                       686 non-null    object
 20  NIVEL_IDEAL_2021               686 non-null    object
 21  DEFASAGEM_2021                 686 non-null    float64
dtypes: float64(2), object(20)
memory usage: 232.0+ KB

In [8]:
# Informação sobre a base
df_passos_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     860 non-null    object
 1   Fase                   860 non-null    int64
 2   Turma                  860 non-null    object
 3   Nome                   860 non-null    object
 4   Ano nasc               860 non-null    int64
 5   Idade 22               860 non-null    int64
 6   Gênero                 860 non-null    object
 7   Ano ingresso           860 non-null    int64
 8   Instituição de ensino  860 non-null    object
 9   Pedra 20               323 non-null    object
 10  Pedra 21               462 non-null    object
 11  Pedra 22               860 non-null    object
 12  INDE 22                860 non-null    float64
 13  Cg                     860 non-null    int64
 14  Cf                     860 non-null    int64
 15  Ct                     860 non-null    int64
 16  Nº Av                  860 non-null    int64
 17  Avaliador1             860 non-null    object
 18  Rec Av1                860 non-null    object
 19  Avaliador2             860 non-null    object
 20  Rec Av2                860 non-null    object
 21  Avaliador3             534 non-null    object
 22  Rec Av3                860 non-null    object
 23  Avaliador4             310 non-null    object
 24  Rec Av4                296 non-null    object
 25  IAA                    860 non-null    float64
 26  IEG                    860 non-null    float64
 27  IPS                    860 non-null    float64
 28  Rec Psicologia         860 non-null    object
 29  IDA                    860 non-null    float64
 30  Matem                  858 non-null    float64
 31  Portug                 858 non-null    float64
 32  Inglês                 283 non-null    float64
 33  Indicado               860 non-null    object
 34  Atingiu PV             860 non-null    object
 35  IPV                    860 non-null    float64
 36  IAN                    860 non-null    float64
 37  Fase ideal             860 non-null    object
 38  Defas                  860 non-null    int64
 39  Destaque IEG           860 non-null    object
 40  Destaque IDA           860 non-null    object
 41  Destaque IPV           860 non-null    object
dtypes: float64(10), int64(9), object(23)
memory usage: 282.3+ KB

In [9]:
# Informação sobre a base
df_passos_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1014 non-null   object
 1   Fase                   1014 non-null   object
 2   INDE 2023              931 non-null    float64
 3   Pedra 2023             931 non-null    object
 4   Turma                  1014 non-null   object
 5   Nome Anonimizado       1014 non-null   object
 6   Data de Nasc           1014 non-null   object
 7   Idade                  1014 non-null   object
 8   Gênero                 1014 non-null   object
 9   Ano ingresso           1014 non-null   int64
 10  Instituição de ensino  1014 non-null   object
 11  Pedra 20               240 non-null    object
 12  Pedra 21               335 non-null    object
 13  Pedra 22               600 non-null    object
 14  Pedra 23               0 non-null      float64
 15  INDE 22                600 non-null    float64
 16  INDE 23                0 non-null      float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  938 non-null    float64
 21  Avaliador1             938 non-null    object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             938 non-null    object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             707 non-null    object
 26  Rec Av3                0 non-null      float64
 27  Avaliador4             334 non-null    object
 28  Rec Av4                0 non-null      float64
 29  IAA                    951 non-null    float64
 30  IEG                    938 non-null    float64
 31  IPS                    945 non-null    float64
 32  IPP                    938 non-null    float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    937 non-null    float64
 35  Mat                    937 non-null    float64
 36  Por                    937 non-null    float64
 37  Ing                    334 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    938 non-null    float64
 41  IAN                    1014 non-null   float64
 42  Fase Ideal             1014 non-null   object
 43  Defasagem              1014 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Destaque IPV.1         0 non-null      float64
dtypes: float64(29), int64(2), object(17)
memory usage: 380.4+ KB

In [10]:
# Informação sobre a base
df_passos_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 50 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1156 non-null   object
 1   Fase                   1156 non-null   object
 2   INDE 2024              1092 non-null   object
 3   Pedra 2024             1092 non-null   object
 4   Turma                  1156 non-null   object
 5   Nome Anonimizado       1156 non-null   object
 6   Data de Nasc           1156 non-null   datetime64[ns]
 7   Idade                  1156 non-null   int64
 8   Gênero                 1156 non-null   object
 9   Ano ingresso           1156 non-null   int64
 10  Instituição de ensino  1155 non-null   object
 11  Pedra 20               191 non-null    object
 12  Pedra 21               264 non-null    object
 13  Pedra 22               472 non-null    object
 14  Pedra 23               690 non-null    object
 15  INDE 22                472 non-null    float64
 16  INDE 23                690 non-null    float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  1156 non-null   int64
 21  Avaliador1             1029 non-null   object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             1029 non-null   object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             793 non-null    object
 26  Avaliador4             407 non-null    object
 27  Avaliador5             148 non-null    object
 28  Avaliador6             6 non-null      object
 29  IAA                    1054 non-null   float64
 30  IEG                    1156 non-null   float64
 31  IPS                    1054 non-null   float64
 32  IPP                    1054 non-null   float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    1055 non-null   float64
 35  Mat                    1051 non-null   float64
 36  Por                    1050 non-null   float64
 37  Ing                    474 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    1054 non-null   float64
 41  IAN                    1156 non-null   float64
 42  Fase Ideal             1156 non-null   object
 43  Defasagem              1156 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Escola                 1155 non-null   object
 48  Ativo/ Inativo         1156 non-null   object
 49  Ativo/ Inativo.1       1156 non-null   object
dtypes: datetime64[ns](1), float64(23), int64(4), object(22)
memory usage: 451.7+ KB

## ENGENHARIA DOS DADOS

In [11]:
# Cópia do dataframe
df_passos_2020_orig = df_passos_2020.copy()
df_passos_2021_orig = df_passos_2021.copy()
df_passos_2022_orig = df_passos_2022.copy()
df_passos_2023_orig = df_passos_2023.copy()
df_passos_2024_orig = df_passos_2024.copy()

### Convertendo colunas

In [12]:
import pandas as pd
import numpy as np
from datetime import datetime, date

# ============================================
# MAPEAMENTO DAS MÉTRICAS POR ANO
# ============================================

bases_metricas = {
    2020: {
        'df': df_passos_2020,
        'colunas': {
            'IAA': 'IAA_2020',
            'IEG': 'IEG_2020',
            'IPS': 'IPS_2020',
            'IDA': 'IDA_2020',
            'IPP': 'IPP_2020',
            'IPV': 'IPV_2020',
            'IAN': 'IAN_2020'
        }
    },

    2021: {
        'df': df_passos_2021,
        'colunas': {
            'IAA': 'IAA_2021',
            'IEG': 'IEG_2021',
            'IPS': 'IPS_2021',
            'IDA': 'IDA_2021',
            'IPP': 'IPP_2021',
            'IPV': 'IPV_2021',
            'IAN': 'IAN_2021'
        }
    },

    2022: {
        'df': df_passos_2022,
        'colunas': {
            'IAA': 'IAA',
            'IEG': 'IEG',
            'IPS': 'IPS',
            'IDA': 'IDA',
            'IPP': 'IPP',
            'IPV': 'IPV',
            'IAN': 'IAN'
        }
    },

    2023: {
        'df': df_passos_2023,
        'colunas': {
            'IAA': 'IAA',
            'IEG': 'IEG',
            'IPS': 'IPS',
            'IDA': 'IDA',
            'IPP': 'IPP',
            'IPV': 'IPV',
            'IAN': 'IAN'
        }
    },

    2024: {
        'df': df_passos_2024,
        'colunas': {
            'IAA': 'IAA',
            'IEG': 'IEG',
            'IPS': 'IPS',
            'IDA': 'IDA',
            'IPP': 'IPP',
            'IPV': 'IPV',
            'IAN': 'IAN'
        }
    }
}


# ============================================
# FUNÇÃO SOMENTE PARA VERIFICAÇÃO
# NÃO ALTERA OS DADOS
# ============================================

def verificar_metrica(serie):

    qtd_data = 0
    qtd_percentual = 0
    qtd_texto_invalido = 0
    qtd_maior_100 = 0

    exemplos_data = []
    exemplos_percentual = []
    exemplos_texto = []
    exemplos_maior_100 = []

    for valor in serie.dropna():

        # Data
        if isinstance(valor, (pd.Timestamp, datetime, date)):
            qtd_data += 1

            if len(exemplos_data) < 5:
                exemplos_data.append(valor)

            continue

        valor_teste = valor

        # Texto
        if isinstance(valor, str):

            valor_teste = valor.strip()

            # %
            if '%' in valor_teste:
                qtd_percentual += 1

                if len(exemplos_percentual) < 5:
                    exemplos_percentual.append(valor)

                valor_teste = valor_teste.replace('%', '')

            valor_teste = valor_teste.replace(',', '.')

        # Tenta converter para número
        numero = pd.to_numeric(valor_teste, errors='coerce')

        # Texto/caractere que não virou número
        if pd.isna(numero):

            qtd_texto_invalido += 1

            if len(exemplos_texto) < 5:
                exemplos_texto.append(valor)

        else:

            # Número maior que 100
            if numero > 100:

                qtd_maior_100 += 1

                if len(exemplos_maior_100) < 5:
                    exemplos_maior_100.append(valor)

    return {
        'Datas': qtd_data,
        'Com %': qtd_percentual,
        'Texto inválido': qtd_texto_invalido,
        'Maior que 100': qtd_maior_100,
        'Exemplo data': exemplos_data,
        'Exemplo %': exemplos_percentual,
        'Exemplo texto': exemplos_texto,
        'Exemplo >100': exemplos_maior_100
    }


# ============================================
# EXECUTAR CONFERÊNCIA
# ============================================

resultado_antes = []

for ano, info in bases_metricas.items():

    df = info['df']

    for metrica, coluna in info['colunas'].items():

        # Algumas bases podem não possuir determinada métrica
        if coluna not in df.columns:
            print(f"{ano} - {metrica}: coluna {coluna} não existe.")
            continue

        verificacao = verificar_metrica(df[coluna])

        resultado_antes.append({
            'Ano': ano,
            'Metrica': metrica,
            'Coluna': coluna,
            **verificacao
        })


df_verificacao_antes = pd.DataFrame(resultado_antes)

display(df_verificacao_antes)

2022 - IPP: coluna IPP não existe.

,Ano,Metrica,Coluna,Datas,Com %,Texto inválido,Maior que 100,Exemplo data,Exemplo %,Exemplo texto,Exemplo >100
0,2020,IAA,IAA_2020,23,0,1,0,"[2025-06-25 00:00:00, 2025-07-05 00:00:00, 202...",[],[D910],[]
1,2020,IEG,IEG_2020,558,0,1,0,"[2025-08-07 00:00:00, 2025-08-09 00:00:00, 202...",[],[V920],[]
2,2020,IPS,IPS_2020,444,0,1,0,"[2025-07-05 00:00:00, 2025-07-05 00:00:00, 202...",[],[D930],[]
3,2020,IDA,IDA_2020,193,0,1,0,"[2025-05-05 00:00:00, 2025-07-05 00:00:00, 202...",[],[D940],[]
4,2020,IPP,IPP_2020,185,0,1,0,"[9375-05-01 00:00:00, 4375-08-01 00:00:00, 437...",[],[D950],[]
5,2020,IPV,IPV_2020,46,0,1,0,"[2025-07-25 00:00:00, 2025-07-05 00:00:00, 202...",[],[D960],[]
6,2020,IAN,IAN_2020,11,0,1,0,"[2025-02-05 00:00:00, 2025-02-05 00:00:00, 202...",[],[D970],[]
7,2021,IAA,IAA_2021,454,0,0,0,"[2025-07-05 00:00:00, 2025-07-01 00:00:00, 202...",[],[],[]
8,2021,IEG,IEG_2021,565,0,0,0,"[2025-06-03 00:00:00, 2025-06-09 00:00:00, 202...",[],[],[]
9,2021,IPS,IPS_2021,634,0,0,0,"[2025-06-09 00:00:00, 2025-06-03 00:00:00, 202...",[],[],[]
10,2021,IDA,IDA_2021,598,0,0,0,"[2025-08-08 00:00:00, 2025-05-06 00:00:00, 202...",[],[],[]
11,2021,IPP,IPP_2021,654,0,0,0,"[2025-07-07 00:00:00, 2025-07-03 00:00:00, 202...",[],[],[]
12,2021,IPV,IPV_2021,634,0,0,0,"[2025-08-01 00:00:00, 2025-07-02 00:00:00, 202...",[],[],[]
13,2021,IAN,IAN_2021,10,0,0,0,"[2025-02-05 00:00:00, 2025-02-05 00:00:00, 202...",[],[],[]
14,2022,IAA,IAA,0,0,0,0,[],[],[],[]
15,2022,IEG,IEG,0,0,0,0,[],[],[],[]
16,2022,IPS,IPS,0,0,0,0,[],[],[],[]
17,2022,IDA,IDA,0,0,0,0,[],[],[],[]
18,2022,IPV,IPV,0,0,0,0,[],[],[],[]
19,2022,IAN,IAN,0,0,0,0,[],[],[],[]
20,2023,IAA,IAA,0,0,0,0,[],[],[],[]
21,2023,IEG,IEG,0,0,0,0,[],[],[],[]
22,2023,IPS,IPS,0,0,0,0,[],[],[],[]
23,2023,IDA,IDA,0,0,0,0,[],[],[],[]
24,2023,IPP,IPP,0,0,0,0,[],[],[],[]
25,2023,IPV,IPV,0,0,0,0,[],[],[],[]
26,2023,IAN,IAN,0,0,0,0,[],[],[],[]
27,2024,IAA,IAA,0,0,0,0,[],[],[],[]
28,2024,IEG,IEG,0,0,0,0,[],[],[],[]
29,2024,IPS,IPS,0,0,0,0,[],[],[],[]
30,2024,IDA,IDA,0,0,0,0,[],[],[],[]
31,2024,IPP,IPP,0,0,0,0,[],[],[],[]
32,2024,IPV,IPV,0,0,0,0,[],[],[],[]
33,2024,IAN,IAN,0,0,0,0,[],[],[],[]

In [13]:
# ============================================
# FUNÇÃO DE CORREÇÃO
# ============================================

def corrigir_metrica(valor):

    # Nulo continua nulo
    if pd.isna(valor):
        return np.nan

    # Excel interpretou nota como data
    if isinstance(valor, (pd.Timestamp, datetime, date)):

        if valor.year <= 2100:
            numero = float(f"{valor.month}.{valor.day}")
        else:
            numero = float(f"{valor.month}.{valor.year}")

    else:

        # Texto
        if isinstance(valor, str):

            valor = (
                valor
                .strip()
                .replace('%', '')
                .replace(',', '.')
            )

        numero = pd.to_numeric(
            valor,
            errors='coerce'
        )

    # Não foi possível converter
    if pd.isna(numero):
        return np.nan

    # Valor maior que 100
    if numero > 100:
        numero = numero / 100

    return float(numero)


# ============================================
# APLICAR NAS MÉTRICAS
# ============================================

for ano, info in bases_metricas.items():

    df = info['df']

    for metrica, coluna in info['colunas'].items():

        if coluna not in df.columns:
            continue

        df[coluna] = (
            df[coluna]
            .apply(corrigir_metrica)
            .astype(float)
        )

In [14]:
# ============================================
# CONFERÊNCIA APÓS A CORREÇÃO
# ============================================

resultado_depois = []

for ano, info in bases_metricas.items():

    df = info['df']

    for metrica, coluna in info['colunas'].items():

        if coluna not in df.columns:
            continue

        serie = df[coluna]

        resultado_depois.append({
            'Ano': ano,
            'Metrica': metrica,
            'Coluna': coluna,
            'Tipo': str(serie.dtype),
            'Qtd nulos': serie.isna().sum(),
            'Menor valor': serie.min(),
            'Maior valor': serie.max(),
            'Qtd > 100': (serie > 100).sum()
        })


df_verificacao_depois = pd.DataFrame(resultado_depois)

display(df_verificacao_depois)

,Ano,Metrica,Coluna,Tipo,Qtd nulos,Menor valor,Maior valor,Qtd > 100
0,2020,IAA,IAA_2020,float64,622,"0,000","10,000",0
1,2020,IEG,IEG_2020,float64,622,"0,000","10,000",0
2,2020,IPS,IPS_2020,float64,622,"2,500","10,000",0
3,2020,IDA,IDA_2020,float64,622,"0,000","10,000",0
4,2020,IPP,IPP_2020,float64,622,"0,000","10,000",0
5,2020,IPV,IPV_2020,float64,622,"0,000","10,000",0
6,2020,IAN,IAN_2020,float64,622,"2,500","10,000",0
7,2021,IAA,IAA_2021,float64,663,"0,000","10,000",0
8,2021,IEG,IEG_2021,float64,663,"0,000","10,000",0
9,2021,IPS,IPS_2021,float64,663,"0,000","8,800",0
10,2021,IDA,IDA_2021,float64,663,"0,000","9,500",0
11,2021,IPP,IPP_2021,float64,663,"0,000","10,000",0
12,2021,IPV,IPV_2021,float64,663,"0,000","10,000",0
13,2021,IAN,IAN_2021,float64,663,"2,500","10,000",0
14,2022,IAA,IAA,float64,0,"0,000","10,000",0
15,2022,IEG,IEG,float64,0,"0,000","10,000",0
16,2022,IPS,IPS,float64,0,"2,500","10,000",0
17,2022,IDA,IDA,float64,0,"0,000","9,900",0
18,2022,IPV,IPV,float64,0,"2,500","10,000",0
19,2022,IAN,IAN,float64,0,"2,500","10,000",0
20,2023,IAA,IAA,float64,63,"0,000","10,000",0
21,2023,IEG,IEG,float64,76,"3,700","10,000",0
22,2023,IPS,IPS,float64,69,"2,520","10,000",0
23,2023,IDA,IDA,float64,77,"0,000","10,000",0
24,2023,IPP,IPP,float64,76,"3,750","9,792",0
25,2023,IPV,IPV,float64,76,"3,320","10,010",0
26,2023,IAN,IAN,float64,0,"2,500","10,000",0
27,2024,IAA,IAA,float64,102,"0,000","10,002",0
28,2024,IEG,IEG,float64,0,"0,000","10,000",0
29,2024,IPS,IPS,float64,102,"2,510","10,000",0
30,2024,IDA,IDA,float64,101,"0,000","10,000",0
31,2024,IPP,IPP,float64,102,"2,500","10,000",0
32,2024,IPV,IPV,float64,102,"2,943","9,760",0
33,2024,IAN,IAN,float64,0,"2,500","10,000",0

In [15]:
# =========================================================
# CONVERSÃO DE COLUNAS DE DATA
# =========================================================

# 2022 - Ano de nascimento
# Como temos apenas o ano, será convertido para 01/01 daquele ano
df_passos_2022['Ano nasc'] = pd.to_datetime(
    df_passos_2022['Ano nasc'].astype(str),
    format='%Y',
    errors='coerce'
)

# 2023 - Data de nascimento
df_passos_2023['Data de Nasc'] = pd.to_datetime(
    df_passos_2023['Data de Nasc'],
    errors='coerce',
    dayfirst=True
)

print(df_passos_2022['Ano nasc'].dtype)
print(df_passos_2023['Data de Nasc'].dtype)

datetime64[ns]
datetime64[ns]

/tmp/ipykernel_5282/3060229917.py:14: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_passos_2023['Data de Nasc'] = pd.to_datetime(

In [16]:
from datetime import datetime, date

# ============================================
# CORREÇÃO DO INDE
# ============================================

def corrigir_inde(valor):

    # Valor vazio
    if pd.isna(valor):
        return np.nan

    # Excel interpretou o INDE como data
    if isinstance(valor, (pd.Timestamp, datetime, date)):

        # Exemplo: 8.7 virou uma data -> mês 8 / dia 7
        if valor.year <= 2100:
            return float(f"{valor.month}.{valor.day}")

        # Mantendo a mesma regra utilizada anteriormente
        else:
            return float(f"{valor.month}.{valor.year}")

    # Caso seja texto
    if isinstance(valor, str):
        valor = (
            valor
            .strip()
            .replace(',', '.')
        )

    # Converter normalmente para número
    return pd.to_numeric(valor, errors='coerce')


# ============================================
# APLICAR NOS 5 DATAFRAMES
# ============================================

colunas_inde = [
    (df_passos_2020, 'INDE_2020'),
    (df_passos_2021, 'INDE_2021'),
    (df_passos_2022, 'INDE 22'),
    (df_passos_2023, 'INDE 2023'),
    (df_passos_2024, 'INDE 2024')
]

for df, coluna in colunas_inde:

    df[coluna] = (
        df[coluna]
        .apply(corrigir_inde)
        .astype(float)
    )

In [17]:
for df, coluna in colunas_inde:

    print(f"\n===== {coluna} =====")
    print("Tipo:", df[coluna].dtype)
    print("Menor valor:", df[coluna].min())
    print("Maior valor:", df[coluna].max())
    print("Qtd nulos:", df[coluna].isna().sum())

===== INDE_2020 =====
Tipo: float64
Menor valor: 3.0650015
Maior valor: 9.712504
Qtd nulos: 622

===== INDE_2021 =====
Tipo: float64
Menor valor: 2.468
Maior valor: 9.294
Qtd nulos: 665

===== INDE 22 =====
Tipo: float64
Menor valor: 3.032
Maior valor: 9.442
Qtd nulos: 0

===== INDE 2023 =====
Tipo: float64
Menor valor: 3.745541667
Maior valor: 9.3712
Qtd nulos: 83

===== INDE 2024 =====
Tipo: float64
Menor valor: 3.7894777778
Maior valor: 9.531325
Qtd nulos: 102

 # Novo dataframe ALUNO_MATERIA #

In [18]:
import pandas as pd
import numpy as np

def process_subjects_for_year(df, year):
    df_subjects_list = []

    # Determine RA column and extract numeric part
    df_RA = None
    if 'NOME' in df.columns:  # For 2020 and 2021
        df_RA = df['NOME'].astype(str).str.replace('ALUNO-', '', regex=False).astype(int)
    elif 'RA' in df.columns:  # For 2022, 2023, 2024
        if pd.api.types.is_string_dtype(df['RA']):
            df_RA = df['RA'].astype(str).str.replace('RA-', '', regex=False).astype(int)
        else:
            df_RA = df['RA'].astype(int)
    else:
        # If no RA column can be determined, return empty DataFrame for subjects
        return pd.DataFrame(columns=['RA', 'Ano', 'Materia', 'Nota'])

    # Define subject column mappings based on year
    subject_cols_map = {}
    if year == 2022:
        subject_cols_map = {'Matem': 'MAT', 'Portug': 'PORT', 'Inglês': 'ING'}
    elif year in [2023, 2024]:
        subject_cols_map = {'Mat': 'MAT', 'Por': 'PORT', 'Ing': 'ING'}
    # For 2020 and 2021, subject_cols_map remains empty, so no subjects will be processed.

    for original_col, materia_name in subject_cols_map.items():
        if original_col in df.columns:
            temp_df = pd.DataFrame({
                'RA': df_RA,
                'Ano': year,
                'Materia': materia_name,
                'Nota': pd.to_numeric(df[original_col], errors='coerce')
            })
            # Drop rows where 'Nota' is NaN (after coerce, these are invalid subject values)
            temp_df.dropna(subset=['Nota'], inplace=True)
            df_subjects_list.append(temp_df)

    return pd.concat(df_subjects_list, ignore_index=True) if df_subjects_list else pd.DataFrame(columns=['RA', 'Ano', 'Materia', 'Nota'])

# Process each year's DataFrame for subjects
aluno_materia_2020 = process_subjects_for_year(df_passos_2020.copy(), 2020)
aluno_materia_2021 = process_subjects_for_year(df_passos_2021.copy(), 2021)
aluno_materia_2022 = process_subjects_for_year(df_passos_2022.copy(), 2022)
aluno_materia_2023 = process_subjects_for_year(df_passos_2023.copy(), 2023)
aluno_materia_2024 = process_subjects_for_year(df_passos_2024.copy(), 2024)

# Concatenate all yearly DataFrames into the final ALUNO_MATERIA DataFrame
ALUNO_MATERIA = pd.concat([
    aluno_materia_2020,
    aluno_materia_2021,
    aluno_materia_2022,
    aluno_materia_2023,
    aluno_materia_2024
], ignore_index=True)

# Ensure RA is integer type if it's not already due to empty dataframes
ALUNO_MATERIA['RA'] = ALUNO_MATERIA['RA'].astype(int)

display(ALUNO_MATERIA.head())

/tmp/ipykernel_5282/3074624440.py:50: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ALUNO_MATERIA = pd.concat([

   RA   Ano Materia  Nota
0   1  2022     MAT 2,700
1   2  2022     MAT 6,300
2   3  2022     MAT 5,800
3   4  2022     MAT 2,800
4   5  2022     MAT 7,000

In [19]:
ALUNO_MATERIA[ALUNO_MATERIA['RA'] == 1]

      RA   Ano Materia  Nota
0      1  2022     MAT 2,700
858    1  2022    PORT 3,500
1716   1  2022     ING 6,000

In [20]:
ALUNO_MATERIA[(ALUNO_MATERIA['Nota'] < 0) | (ALUNO_MATERIA['Nota'] > 10)]

Empty DataFrame
Columns: [RA, Ano, Materia, Nota]
Index: []

# Novo dataframe ALUNO_METRICA #

In [21]:
import pandas as pd
import numpy as np

def process_metrics_for_year(df, year):
    df_metrics_list = []

    # Handle RA extraction based on year/dataframe structure
    df_RA = None
    if 'NOME' in df.columns: # This covers 2020 and 2021 where RA is derived from NOME
        # Ensure 'NOME' values are strings before applying .str.replace
        df_RA = df['NOME'].astype(str).str.replace('ALUNO-', '', regex=False).astype(int)
    elif 'RA' in df.columns: # This covers 2022, 2023, 2024 where RA is a direct column
        if pd.api.types.is_string_dtype(df['RA']):
            df_RA = df['RA'].astype(str).str.replace('RA-', '', regex=False).astype(int)
        else:
            df_RA = df['RA'].astype(int)
    else:
        print(f"Error: Could not find 'RA' or 'NOME' column for RA extraction in year {year}. Returning empty DataFrame.")
        return pd.DataFrame(columns=['RA', 'Ano', 'Metrica', 'Nota', 'Destaque'])

    # Define metric and corresponding Destaque column names based on the year
    metric_col_name_map = {} # Maps standard metric name (e.g., 'IAA') to actual column in df (e.g., 'IAA_2020' or 'IAA')
    destaque_col_name_map = {} # Maps standard metric name (e.g., 'IAA') to actual Destaque column in df (e.g., 'Destaque_IAA_2020' or 'Destaque IAA')

    if year == 2020:
        metric_col_name_map = {
            'IAA': 'IAA_2020', 'IEG': 'IEG_2020', 'IPS': 'IPS_2020',
            'IDA': 'IDA_2020', 'IPP': 'IPP_2020', 'IPV': 'IPV_2020',
            'IAN': 'IAN_2020'
        }
        # Only include Destaque columns specifically requested for 2020
        destaque_col_name_map = {
            'IEG': 'DESTAQUE_IEG_2020',
            'IDA': 'DESTAQUE_IDA_2020',
            'IPV': 'DESTAQUE_IPV_2020'
        }
    elif year == 2021:
        metric_col_name_map = {
            'IAA': 'IAA_2021', 'IEG': 'IEG_2021', 'IPS': 'IPS_2021',
            'IDA': 'IDA_2021', 'IPP': 'IPP_2021', 'IPV': 'IPV_2021',
            'IAN': 'IAN_2021'
        }
        # Only include Destaque columns specifically requested for 2021
        destaque_col_name_map = {
            'IEG': 'DESTAQUE_IEG_2021',
            'IDA': 'DESTAQUE_IDA_2021',
            'IPV': 'DESTAQUE_IPV_2021'
        }
    else: # For 2022, 2023, 2024 - use existing mappings
        metric_col_name_map = {
            'IAA': 'IAA', 'IEG': 'IEG', 'IPP': 'IPP',
            'IPV': 'IPV', 'IPS': 'IPS', 'IDA': 'IDA',
            'IAN': 'IAN'
        }
        destaque_col_name_map = {
            'IAA': 'Destaque IAA', 'IEG': 'Destaque IEG', 'IPP': 'Destaque IPP',
            'IPV': 'Destaque IPV', 'IPS': 'Destaque IPS', 'IDA': 'Destaque IDA',
            'IAN': 'Destaque IAN'
        }

    for standard_metric_name, actual_metric_col in metric_col_name_map.items():
        if actual_metric_col in df.columns:
            temp_metric_df = pd.DataFrame({
                'RA': df_RA,
                'Ano': year,
                'Metrica': standard_metric_name,
                'Nota': pd.to_numeric(df[actual_metric_col], errors='coerce')
            })

            # Initialize 'Destaque' column with pd.NA
            temp_metric_df['Destaque'] = pd.NA

            destaque_col_name_for_metric = destaque_col_name_map.get(standard_metric_name)

            # Check if the specific Destaque column exists for the metric and is not entirely null
            if destaque_col_name_for_metric and destaque_col_name_for_metric in df.columns:
                # Only assign if the column is not entirely null
                if not df[destaque_col_name_for_metric].isnull().all():
                    temp_metric_df['Destaque'] = df[destaque_col_name_for_metric]


            # Drop rows where 'Nota' is NaN (after coerce, these are invalid metric values)
            temp_metric_df.dropna(subset=['Nota'], inplace=True)
            df_metrics_list.append(temp_metric_df)

    return pd.concat(df_metrics_list, ignore_index=True) if df_metrics_list else pd.DataFrame(columns=['RA', 'Ano', 'Metrica', 'Nota', 'Destaque'])


# Process all df_passos dataframes
aluno_metrica_2020 = process_metrics_for_year(df_passos_2020.copy(), 2020)
aluno_metrica_2021 = process_metrics_for_year(df_passos_2021.copy(), 2021)
aluno_metrica_2022 = process_metrics_for_year(df_passos_2022.copy(), 2022)
aluno_metrica_2023 = process_metrics_for_year(df_passos_2023.copy(), 2023)
aluno_metrica_2024 = process_metrics_for_year(df_passos_2024.copy(), 2024)

# Concatenate all yearly DataFrames into the final ALUNO_METRICA DataFrame
ALUNO_METRICA = pd.concat([
    aluno_metrica_2020,
    aluno_metrica_2021,
    aluno_metrica_2022,
    aluno_metrica_2023,
    aluno_metrica_2024
], ignore_index=True)

# Display the first few rows of the updated ALUNO_METRICA DataFrame
display(ALUNO_METRICA.head())

   RA   Ano Metrica  Nota Destaque
0   1  2020     IAA 8,500      NaN
1   3  2020     IAA 7,917      NaN
2   4  2020     IAA 8,000      NaN
3   5  2020     IAA 7,500      NaN
4   8  2020     IAA 8,333      NaN

In [22]:
ALUNO_METRICA.loc[ALUNO_METRICA['Nota'] > 10, 'Nota'] = 10

### Incluindo coluna de Status_metrica no dataframe ALUNO_METRICA

In [23]:
#
# Quando Metrica=IAN e Nota = 10  então Status_metrica = "Em fase"
# Quando Metrica=IAN e Nota = 5   então Status_metrica = "Moderada"
# Quando Metrica=IAN e Nota = 2,5 então Status_metrica = "Severa"
#



# Criar coluna Status_metrica
ALUNO_METRICA['Status_metrica'] = pd.NA

ALUNO_METRICA.loc[
    (ALUNO_METRICA['Metrica'] == 'IAN') &
    (ALUNO_METRICA['Nota'] == 10),
    'Status_metrica'
] = 'Em fase'

ALUNO_METRICA.loc[
    (ALUNO_METRICA['Metrica'] == 'IAN') &
    (ALUNO_METRICA['Nota'] == 5),
    'Status_metrica'
] = 'Moderada'

ALUNO_METRICA.loc[
    (ALUNO_METRICA['Metrica'] == 'IAN') &
    (ALUNO_METRICA['Nota'] == 2.5),
    'Status_metrica'
] = 'Severa'


display(ALUNO_METRICA.head())

   RA   Ano Metrica  Nota Destaque Status_metrica
0   1  2020     IAA 8,500      NaN           <NA>
1   3  2020     IAA 7,917      NaN           <NA>
2   4  2020     IAA 8,000      NaN           <NA>
3   5  2020     IAA 7,500      NaN           <NA>
4   8  2020     IAA 8,333      NaN           <NA>

In [24]:
ALUNO_METRICA[
    (ALUNO_METRICA['Metrica'] == 'IAN')
   & (ALUNO_METRICA['RA'] == 1)
]

       RA   Ano Metrica   Nota Destaque Status_metrica
4362    1  2020     IAN 10,000      NaN        Em fase
9205    1  2021     IAN  5,000      NaN       Moderada
14191   1  2022     IAN  5,000      NaN       Moderada
21693   1  2023     IAN 10,000      NaN        Em fase
29223   1  2024     IAN 10,000      NaN        Em fase

In [25]:
ALUNO_METRICA.loc[ALUNO_METRICA['RA'] == 1]

,RA,Ano,Metrica,Nota,Destaque,Status_metrica
0,1,2020,IAA,"8,500",NaN,<NA>
727,1,2020,IEG,"8,700",Seu destaque em 2020: A sua boa entrega das li...,<NA>
1454,1,2020,IPS,"7,500",NaN,<NA>
2181,1,2020,IDA,"7,000",Ponto a melhorar em 2021: Empenhar-se mais nas...,<NA>
2908,1,2020,IPP,"5,938",NaN,<NA>
3635,1,2020,IPV,"7,750",Seu destaque em 2020: A sua boa integração aos...,<NA>
4362,1,2020,IAN,"10,000",NaN,Em fase
5089,1,2021,IAA,"7,500",NaN,<NA>
5775,1,2021,IEG,"6,300",NaN,<NA>
6461,1,2021,IPS,"6,900",NaN,<NA>
7147,1,2021,IDA,"8,800",NaN,<NA>
7833,1,2021,IPP,"7,700",NaN,<NA>
8519,1,2021,IPV,"8,100",NaN,<NA>
9205,1,2021,IAN,"5,000",NaN,Moderada
9891,1,2022,IAA,"8,300",NaN,<NA>
10751,1,2022,IEG,"4,100",Melhorar: Melhorar a sua entrega de lições de ...,<NA>
11611,1,2022,IPV,"7,278",Melhorar: Integrar-se mais aos Princípios Pass...,<NA>
12471,1,2022,IPS,"5,600",NaN,<NA>
13331,1,2022,IDA,"4,000",Melhorar: Empenhar-se mais nas aulas e avaliaç...,<NA>
14191,1,2022,IAN,"5,000",NaN,Moderada
21693,1,2023,IAN,"10,000",NaN,Em fase
23850,1,2024,IEG,"0,000",NaN,<NA>
29223,1,2024,IAN,"10,000",NaN,Em fase

Verificando os valores de IDA do dataframe ALUNO_METRICA

In [26]:
# ============================================================
# CHECAGEM IDA = 0
# E pelo menos uma nota MAT / PORT / ING diferente de zero
# ============================================================


# ----------------------------
# 2022
# ----------------------------

check_2022 = df_passos_2022[
    (df_passos_2022['IDA'] == 0) &
    (
        (df_passos_2022['Matem'].notna() & (df_passos_2022['Matem'] != 0)) |
        (df_passos_2022['Portug'].notna() & (df_passos_2022['Portug'] != 0)) |
        (df_passos_2022['Inglês'].notna() & (df_passos_2022['Inglês'] != 0))
    )
][
    ['RA', 'IDA', 'Matem', 'Portug', 'Inglês']
].copy()

check_2022['Ano'] = 2022

check_2022 = check_2022.rename(columns={
    'Matem': 'MAT',
    'Portug': 'PORT',
    'Inglês': 'ING'
})


# ----------------------------
# 2023
# ----------------------------

check_2023 = df_passos_2023[
    (df_passos_2023['IDA'] == 0) &
    (
        (df_passos_2023['Mat'].notna() & (df_passos_2023['Mat'] != 0)) |
        (df_passos_2023['Por'].notna() & (df_passos_2023['Por'] != 0)) |
        (df_passos_2023['Ing'].notna() & (df_passos_2023['Ing'] != 0))
    )
][
    ['RA', 'IDA', 'Mat', 'Por', 'Ing']
].copy()

check_2023['Ano'] = 2023

check_2023 = check_2023.rename(columns={
    'Mat': 'MAT',
    'Por': 'PORT',
    'Ing': 'ING'
})


# ----------------------------
# 2024
# ----------------------------

check_2024 = df_passos_2024[
    (df_passos_2024['IDA'] == 0) &
    (
        (df_passos_2024['Mat'].notna() & (df_passos_2024['Mat'] != 0)) |
        (df_passos_2024['Por'].notna() & (df_passos_2024['Por'] != 0)) |
        (df_passos_2024['Ing'].notna() & (df_passos_2024['Ing'] != 0))
    )
][
    ['RA', 'IDA', 'Mat', 'Por', 'Ing']
].copy()

check_2024['Ano'] = 2024

check_2024 = check_2024.rename(columns={
    'Mat': 'MAT',
    'Por': 'PORT',
    'Ing': 'ING'
})


# ============================================================
# JUNTAR OS 3 ANOS
# ============================================================

checagem_ida = pd.concat(
    [
        check_2022,
        check_2023,
        check_2024
    ],
    ignore_index=True
)


# Organizar as colunas
checagem_ida = checagem_ida[
    ['RA', 'Ano', 'IDA', 'MAT', 'PORT', 'ING']
]


# Mostrar resultado
display(checagem_ida)

Empty DataFrame
Columns: [RA, Ano, IDA, MAT, PORT, ING]
Index: []

## Incluindo o status para IPS comparando com o ano anterior

In [27]:
# ============================================
# STATUS DE EVOLUÇÃO DO IPS
# ============================================

# Selecionar somente IPS
mask_ips = ALUNO_METRICA['Metrica'].eq('IPS')

# Criar dataframe auxiliar
ips = (
    ALUNO_METRICA.loc[
        mask_ips,
        ['RA', 'Ano', 'Nota']
    ]
    .copy()
    .sort_values(['RA', 'Ano'])
)

# Nota e ano anteriores do mesmo aluno
ips['Nota_anterior'] = (
    ips.groupby('RA')['Nota']
    .shift(1)
)

ips['Ano_anterior'] = (
    ips.groupby('RA')['Ano']
    .shift(1)
)

# Verificar se realmente é o ano imediatamente anterior
ano_consecutivo = (
    ips['Ano_anterior'] == ips['Ano'] - 1
)

# Começa como "Sem histórico"
ips['Status_IPS'] = 'Sem histórico'

# Piorou
ips.loc[
    ano_consecutivo &
    (ips['Nota'] < ips['Nota_anterior']),
    'Status_IPS'
] = 'Piorou'

# Melhorou
ips.loc[
    ano_consecutivo &
    (ips['Nota'] > ips['Nota_anterior']),
    'Status_IPS'
] = 'Melhorou'

# Manteve
ips.loc[
    ano_consecutivo &
    (ips['Nota'] == ips['Nota_anterior']),
    'Status_IPS'
] = 'Manteve'


# Gravar de volta na ALUNO_METRICA
ALUNO_METRICA.loc[
    ips.index,
    'Status_metrica'
] = ips['Status_IPS']

In [28]:
ALUNO_METRICA[
    ALUNO_METRICA['Metrica'] == 'IPS'
][
    ['RA', 'Ano', 'Metrica', 'Nota', 'Status_metrica']
].sort_values(['RA', 'Ano']).head(30)

       RA   Ano Metrica  Nota Status_metrica
1454    1  2020     IPS 7,500  Sem histórico
6461    1  2021     IPS 6,900         Piorou
12471   1  2022     IPS 5,600         Piorou
12472   2  2022     IPS 6,300  Sem histórico
1455    3  2020     IPS 7,500  Sem histórico
6462    3  2021     IPS 6,300         Piorou
12473   3  2022     IPS 5,600         Piorou
1456    4  2020     IPS 6,875  Sem histórico
12474   4  2022     IPS 5,600  Sem histórico
1457    5  2020     IPS 7,500  Sem histórico
6463    5  2021     IPS 7,500        Manteve
12475   5  2022     IPS 5,600         Piorou
12476   6  2022     IPS 7,500  Sem histórico
12477   7  2022     IPS 7,500  Sem histórico
1458    8  2020     IPS 4,375  Sem histórico
6464    8  2021     IPS 7,500       Melhorou
12478   8  2022     IPS 6,300         Piorou
12479   9  2022     IPS 7,500  Sem histórico
1459   10  2020     IPS 3,750  Sem histórico
12480  10  2022     IPS 5,000  Sem histórico
1460   11  2020     IPS 8,125  Sem histórico
6465   11  2021     IPS 6,300         Piorou
12481  11  2022     IPS 5,000         Piorou
1461   12  2020     IPS 5,625  Sem histórico
12482  12  2022     IPS 6,900  Sem histórico
6466   13  2021     IPS 7,500  Sem histórico
12483  13  2022     IPS 7,500        Manteve
1462   14  2020     IPS 6,875  Sem histórico
12484  14  2022     IPS 7,500  Sem histórico
1463   15  2020     IPS 7,500  Sem histórico

In [29]:
ALUNO_METRICA[
    (ALUNO_METRICA['Metrica'] == 'IPS') &
    (ALUNO_METRICA['RA'] == 480)
][
    ['RA', 'Ano', 'Metrica', 'Nota', 'Status_metrica']
].sort_values(['Ano'])

        RA   Ano Metrica  Nota Status_metrica
12950  480  2022     IPS 7,500  Sem histórico
19062  480  2023     IPS 7,520       Melhorou
26436  480  2024     IPS 7,510         Piorou

# Novo dataframe ALUNO_AVALIACAO #

In [30]:
def process_avaliacoes_new(df, year):
    df_avaliacoes_list = []

    # Ensure 'RA' column exists before processing
    if 'RA' not in df.columns:
        print(f"Warning: 'RA' column not found in DataFrame for year {year}. Skipping.")
        return pd.DataFrame(columns=['RA', 'Ano', 'Avaliador', 'Nome_avaliador', 'Resultado'])

    # Handle RA extraction based on year/dataframe structure
    df_RA = None
    if pd.api.types.is_string_dtype(df['RA']):
        df_RA = df['RA'].astype(str).str.replace('RA-', '', regex=False).astype(int)
    else:
        df_RA = df['RA'].astype(int)

    # Iterate through Avaliador columns (1 to 6)
    for i in range(1, 7):
        avaliador_col_name = f'Avaliador{i}'
        rec_av_col_name = f'Rec Av{i}'

        if avaliador_col_name in df.columns:
            temp_df = pd.DataFrame({
                'RA': df_RA,
                'Ano': year,
                'Avaliador': i, # Numeric Avaliador ID
                'Nome_avaliador': df[avaliador_col_name],
            })

            # If the corresponding 'Rec AvX' column exists, populate 'Resultado'
            if rec_av_col_name in df.columns:
                temp_df['Resultado'] = df[rec_av_col_name]
            else:
                temp_df['Resultado'] = pd.NA # Set to NA if 'Rec AvX' does not exist

            # Drop rows where 'Nome_avaliador' is NaN, as an Avaliador must exist for an entry
            temp_df.dropna(subset=['Nome_avaliador'], inplace=True)
            df_avaliacoes_list.append(temp_df)

    return pd.concat(df_avaliacoes_list, ignore_index=True) if df_avaliacoes_list else pd.DataFrame(columns=['RA', 'Ano', 'Avaliador', 'Nome_avaliador', 'Resultado'])

# Process each year's DataFrame
aluno_avaliacao_2022_new = process_avaliacoes_new(df_passos_2022.copy(), 2022)
aluno_avaliacao_2023_new = process_avaliacoes_new(df_passos_2023.copy(), 2023)
aluno_avaliacao_2024_new = process_avaliacoes_new(df_passos_2024.copy(), 2024)

# Concatenate all yearly DataFrames into the final ALUNO_AVALIACAO DataFrame
ALUNO_AVALIACAO = pd.concat([aluno_avaliacao_2022_new, aluno_avaliacao_2023_new, aluno_avaliacao_2024_new], ignore_index=True)

# Display the first few rows of the new DataFrame
display(ALUNO_AVALIACAO.head())

   RA   Ano  Avaliador Nome_avaliador              Resultado
0   1  2022          1    Avaliador-5  Mantido na Fase atual
1   2  2022          1    Avaliador-5      Promovido de Fase
2   3  2022          1    Avaliador-5      Promovido de Fase
3   4  2022          1    Avaliador-5      Promovido de Fase
4   5  2022          1    Avaliador-5      Promovido de Fase

### Incluindo dados de avaliação de 2021 para ALUNO_AVALIACAO

Agora, vamos processar os dados de avaliação do ano de 2021 para incluir no DataFrame `ALUNO_AVALIACAO`.

In [31]:
def process_avaliacoes_2021(df, year):
    df_avaliacoes_list = []

    # Extrair RA da coluna NOME para 2021 (ex: 'ALUNO-1' -> 1)
    if 'NOME' not in df.columns:
        print(f"Aviso: Coluna 'NOME' não encontrada no DataFrame para o ano {year}. Ignorando.")
        return pd.DataFrame(columns=['RA', 'Ano', 'Avaliador', 'Nome_avaliador', 'Resultado'])

    df_RA = df['NOME'].astype(str).str.replace('ALUNO-', '', regex=False).astype(int)

    # Mapeamento das colunas REC_EQUIPE e os IDs dos avaliadores
    rec_equipe_cols = {
        1: 'REC_EQUIPE_1_2021',
        2: 'REC_EQUIPE_2_2021',
        3: 'REC_EQUIPE_3_2021',
        4: 'REC_EQUIPE_4_2021'
    }

    for avaliador_id, rec_col_name in rec_equipe_cols.items():
        if rec_col_name in df.columns:
            # Criar um DataFrame temporário para este avaliador e coluna de recomendação
            temp_df = pd.DataFrame({
                'RA': df_RA,
                'Ano': year,
                'Avaliador': avaliador_id,
                'Nome_avaliador': pd.NA, # Não há coluna de nome de avaliador explícita para 2021
                'Resultado': df[rec_col_name]
            })
            # Remover linhas onde 'Resultado' é NaN, pois só queremos entradas com resultado
            temp_df.dropna(subset=['Resultado'], inplace=True)
            df_avaliacoes_list.append(temp_df)

    return pd.concat(df_avaliacoes_list, ignore_index=True) if df_avaliacoes_list else pd.DataFrame(columns=['RA', 'Ano', 'Avaliador', 'Nome_avaliador', 'Resultado'])

In [32]:
# Processar os dados de 2021
aluno_avaliacao_2021_new = process_avaliacoes_2021(df_passos_2021.copy(), 2021)

# Concatenar os dados de 2021 com o DataFrame ALUNO_AVALIACAO existente
ALUNO_AVALIACAO = pd.concat([aluno_avaliacao_2021_new, ALUNO_AVALIACAO], ignore_index=True)

# Exibir as primeiras linhas do DataFrame ALUNO_AVALIACAO atualizado
display(ALUNO_AVALIACAO.head())

   RA   Ano  Avaliador Nome_avaliador                  Resultado
0   1  2021          1            NaN          Promovido de Fase
1   3  2021          1            NaN          Promovido de Fase
2   5  2021          1            NaN          Promovido de Fase
3   8  2021          1            NaN  Promovido de Fase + Bolsa
4  11  2021          1            NaN          Promovido de Fase

In [33]:
ALUNO_AVALIACAO['Nome_avaliador'].unique()

array([nan, 'Avaliador-5', 'Avaliador-6', 'Avaliador-4', 'Avaliador-7',
       'Avaliador-11', 'Avaliador-13', 'Avaliador-27', 'Avaliador-30',
       'Avaliador-2', 'Avaliador-3', 'Avaliador-28', 'Avaliador-29',
       'Avaliador-24', 'Avaliador-31', 'Avaliador-15', 'Avaliador-19',
       'Avaliador-32', 'Avaliador-21', 'Avaliador-34', 'Avaliador-23',
       'Avaliador-8', 'Avaliador-12', 'Avaliador-14', 'Avaliador-16',
       'Avaliador-17', 'Avaliador-18', 'Avaliador-20', 'Avaliador-22',
       'Avaliador-25', 'Avaliador-26', 'Avaliador-1', 'Avaliador-9',
       'Avaliador-10'], dtype=object)

In [34]:
ALUNO_AVALIACAO['Resultado'].unique()

array(['Promovido de Fase', 'Promovido de Fase + Bolsa', 'Não avaliado',
       'Mantido na Fase atual', 'Mantido na Fase + Bolsa',
       'Alocado em Fase anterior', nan], dtype=object)

In [35]:
ALUNO_AVALIACAO.loc[ALUNO_AVALIACAO['RA'] == 1]

      RA   Ano  Avaliador Nome_avaliador                  Resultado
0      1  2021          1            NaN          Promovido de Fase
686    1  2021          2            NaN          Promovido de Fase
1372   1  2021          3            NaN      Mantido na Fase atual
2058   1  2021          4            NaN               Não avaliado
2744   1  2022          1    Avaliador-5      Mantido na Fase atual
3604   1  2022          2   Avaliador-27  Promovido de Fase + Bolsa
4464   1  2022          3   Avaliador-28          Promovido de Fase
4998   1  2022          4   Avaliador-31      Mantido na Fase atual

# Novo dataframe ALUNO_PEDRA #

In [36]:
def process_pedra_data(df, year, pedra_col_name):
    # Determine RA column and extract numeric part
    df_RA = None
    if 'NOME' in df.columns:  # For 2020 and 2021
        df_RA = df['NOME'].astype(str).str.replace('ALUNO-', '', regex=False).astype(int)
    elif 'RA' in df.columns:  # For 2022, 2023, 2024
        if pd.api.types.is_string_dtype(df['RA']):
            df_RA = df['RA'].astype(str).str.replace('RA-', '', regex=False).astype(int)
        else:
            df_RA = df['RA'].astype(int)
    else:
        print(f"Error: Could not find 'RA' or 'NOME' column for RA extraction in year {year}. Skipping.")
        return pd.DataFrame(columns=['RA', 'Ano', 'Pedra'])

    if pedra_col_name not in df.columns:
        print(f"Warning: '{pedra_col_name}' column not found in DataFrame for year {year}. Skipping.")
        return pd.DataFrame(columns=['RA', 'Ano', 'Pedra'])

    temp_df = pd.DataFrame({
        'RA': df_RA,
        'Ano': year,
        'Pedra': df[pedra_col_name]
    })
    # Drop rows where 'Pedra' is NaN, as we only want entries with a recorded 'Pedra'
    temp_df.dropna(subset=['Pedra'], inplace=True)
    return temp_df

# Process data for each year
aluno_pedra_2020 = process_pedra_data(df_passos_2020.copy(), 2020, 'PEDRA_2020')
aluno_pedra_2021 = process_pedra_data(df_passos_2021.copy(), 2021, 'PEDRA_2021')
aluno_pedra_2022 = process_pedra_data(df_passos_2022.copy(), 2022, 'Pedra 22')
aluno_pedra_2023 = process_pedra_data(df_passos_2023.copy(), 2023, 'Pedra 2023')
aluno_pedra_2024 = process_pedra_data(df_passos_2024.copy(), 2024, 'Pedra 2024')

# Concatenate all yearly DataFrames into the final ALUNO_PEDRA DataFrame
ALUNO_PEDRA = pd.concat([aluno_pedra_2020, aluno_pedra_2021, aluno_pedra_2022, aluno_pedra_2023, aluno_pedra_2024], ignore_index=True)

# Display the first few rows of the new DataFrame
display(ALUNO_PEDRA.head())

   RA   Ano     Pedra
0   1  2020  Ametista
1   3  2020  Ametista
2   4  2020   Quartzo
3   5  2020  Ametista
4   8  2020  Ametista

In [37]:
ALUNO_PEDRA['Pedra'].unique()

array(['Ametista', 'Quartzo', 'Topázio', 'Ágata', 'D9891/2A', '#NULO!',
       'Agata', 'INCLUIR'], dtype=object)

In [38]:
ALUNO_PEDRA.loc[ALUNO_PEDRA['Pedra'] == 'Agata', 'Pedra'] = 'Ágata'

display(ALUNO_PEDRA['Pedra'].unique())

array(['Ametista', 'Quartzo', 'Topázio', 'Ágata', 'D9891/2A', '#NULO!',
       'INCLUIR'], dtype=object)

In [39]:
ALUNO_PEDRA.loc[ALUNO_PEDRA['RA'] == 1]

      RA   Ano     Pedra
0      1  2020  Ametista
728    1  2021  Ametista
1414   1  2022   Quartzo

# Novo dataframe ALUNO #

In [40]:
def process_aluno_data(df, year):
    temp_aluno_df = pd.DataFrame()

    # RA column extraction and standardization
    if year in [2022, 2023, 2024]:
        # For 2022, 2023, 2024: 'RA' column (e.g., 'RA-1' -> 1)
        temp_aluno_df['RA'] = df['RA'].astype(str).str.replace('RA-', '', regex=False).astype(int)
    elif year in [2020, 2021]:
        # For 2020, 2021: 'NOME' column (e.g., 'ALUNO-1' -> 1)
        temp_aluno_df['RA'] = df['NOME'].astype(str).str.replace('ALUNO-', '', regex=False).astype(int)

    # Nome_aluno column extraction
    if year == 2022:
        temp_aluno_df['Nome_aluno'] = df['Nome']
    elif year in [2023, 2024]:
        temp_aluno_df['Nome_aluno'] = df['Nome Anonimizado']
    elif year in [2020, 2021]:
        temp_aluno_df['Nome_aluno'] = df['NOME']

    # Nascimento column extraction
    if year == 2022:
        temp_aluno_df['Nascimento'] = df['Ano nasc']
    elif year in [2023, 2024]:
        temp_aluno_df['Nascimento'] = df['Data de Nasc']
    else:
        # No direct birth date column for 2020 and 2021 in original dfs
        temp_aluno_df['Nascimento'] = pd.NaT # Not a Time

    # Genero column extraction and standardization
    if 'Gênero' in df.columns:
        temp_aluno_df['Genero'] = df['Gênero']
        temp_aluno_df['Genero'] = temp_aluno_df['Genero'].replace({'Menina': 'Feminino', 'Menino': 'Masculino'})
    else:
        # No 'Gênero' column for 2020 and 2021
        temp_aluno_df['Genero'] = pd.NA

    # Add the year column for sorting and aggregation
    temp_aluno_df['Ano'] = year

    return temp_aluno_df

# Process each year's DataFrame
aluno_2020 = process_aluno_data(df_passos_2020.copy(), 2020)
aluno_2021 = process_aluno_data(df_passos_2021.copy(), 2021)
aluno_2022 = process_aluno_data(df_passos_2022.copy(), 2022)
aluno_2023 = process_aluno_data(df_passos_2023.copy(), 2023)
aluno_2024 = process_aluno_data(df_passos_2024.copy(), 2024)

# Concatenate all yearly DataFrames into a temporary DataFrame
ALUNO_temp = pd.concat([aluno_2020, aluno_2021, aluno_2022, aluno_2023, aluno_2024], ignore_index=True)

# Sort by RA and Year to ensure proper aggregation order
# For Nome_aluno, we want the *first* non-null (e.g., 'ALUNO-1' over 'Aluno-1')
# For Nascimento and Genero, we want the *last* non-null (most recent/complete)
ALUNO_temp = ALUNO_temp.sort_values(by=['RA', 'Ano'])

# Group by RA and aggregate to get a single, most complete record per student
ALUNO = ALUNO_temp.groupby('RA').agg({
    'Nome_aluno': lambda x: x.dropna().iloc[0] if not x.dropna().empty else pd.NA,
    'Nascimento': lambda x: x.dropna().iloc[-1] if not x.dropna().empty else pd.NaT,
    'Genero': lambda x: x.dropna().iloc[-1] if not x.dropna().empty else pd.NA
}).reset_index()

# Ensure 'RA' column is of integer type
ALUNO['RA'] = ALUNO['RA'].astype(int)

# Convert 'Nascimento' to datetime if not already, then format to 'dd/mm/yyyy'
ALUNO['Nascimento'] = pd.to_datetime(ALUNO['Nascimento'], errors='coerce')
ALUNO['Nascimento'] = ALUNO['Nascimento'].dt.strftime('%d/%m/%Y')

# Display the first few rows of the ALUNO DataFrame
display(ALUNO.head())

   RA Nome_aluno  Nascimento     Genero
0   1    ALUNO-1  03/10/2003   Feminino
1   2    ALUNO-2  17/05/2005   Feminino
2   3    ALUNO-3  01/01/2005   Feminino
3   4    ALUNO-4  01/01/2005  Masculino
4   5    ALUNO-5  01/12/2005   Feminino

In [41]:
ALUNO.loc[ALUNO['RA'] == 1]

   RA Nome_aluno  Nascimento    Genero
0   1    ALUNO-1  03/10/2003  Feminino

# Novo dataframe ALUNO_PASSOS #

In [42]:
df_passos_2024['Fase'].unique()

array(['ALFA', '1A', '1B', '1C', '1D', '1E', '1G', '1H', '1J', '1K', '1L',
       '1M', '1N', '1P', '1R', '2A', '2B', '2C', '2D', '2G', '2H', '2I',
       '2K', '2L', '2M', '2N', '2P', '2R', '2U', '3A', '3B', '3C', '3D',
       '3F', '3G', '3H', '3I', '3K', '3L', '3M', '3N', '3P', '3R', '3U',
       '4A', '4B', '4C', '4F', '4H', '4L', '4M', '4N', '4R', '5A', '5B',
       '5C', '5D', '5F', '5G', '5L', '5M', '5N', '6A', '6L', '7A', '7E',
       '8A', '8B', '8D', '8E', '8F', 9], dtype=object)

In [43]:
def process_passos_data(df, year):
    temp_passos_df = pd.DataFrame()

    # --- RA (Nr inteiro) ---
    if year in [2020, 2021]:
        # For 2020, 2021: 'NOME' column (e.g., 'ALUNO-1' -> 1)
        temp_passos_df['RA'] = df.get('NOME', pd.Series(index=df.index, dtype=object)).astype(str).str.replace('ALUNO-', '', regex=False).astype(int)
    elif year in [2022, 2023, 2024]:
        # For 2022, 2023, 2024: 'RA' column (e.g., 'RA-1' -> 1)
        temp_passos_df['RA'] = df.get('RA', pd.Series(index=df.index, dtype=object)).astype(str).str.replace('RA-', '', regex=False).astype(int)

    # --- Ano (Nr inteiro) ---
    temp_passos_df['Ano'] = year

    # --- INDE (decimal) ---
    inde_col = None
    if year == 2020:
        inde_col = 'INDE_2020'
    elif year == 2021:
        inde_col = 'INDE_2021'
    elif year == 2022:
        inde_col = 'INDE 22'
    elif year == 2023:
        inde_col = 'INDE 2023'
    elif year == 2024:
        inde_col = 'INDE 2024'
    temp_passos_df['INDE'] = pd.to_numeric(df.get(inde_col, pd.Series(index=df.index, dtype=object)), errors='coerce')


    # --- Fase (Nr inteiro) ---
    if year == 2020:
        # Ex.: "2H" -> 2
        fase_raw = df.get(
            'FASE_TURMA_2020',
            pd.Series(index=df.index, dtype=object)
        ).astype(str)

        fase_series = fase_raw.str.extract(r'(\d+)', expand=False)

        temp_passos_df['Fase'] = (
            pd.to_numeric(fase_series, errors='coerce')
            .astype('Int64')
        )

    elif year == 2021:
        # Ex.: 2.0 -> 2
        temp_passos_df['Fase'] = (
            pd.to_numeric(
                df.get(
                    'FASE_2021',
                    pd.Series(index=df.index, dtype=object)
                ),
                errors='coerce'
            )
            .astype('Int64')
        )

    elif year == 2022:
        # Mantém o valor numérico da coluna Fase
        temp_passos_df['Fase'] = (
            pd.to_numeric(
                df.get(
                    'Fase',
                    pd.Series(index=df.index, dtype=object)
                ),
                errors='coerce'
            )
            .astype('Int64')
        )

    elif year == 2023:
        # Regras:
        # "FASE 1" -> 1
        # "FASE 2" -> 2
        # "ALFA"   -> 0
        # Nulo     -> nulo

        fase_raw = (
            df['Fase']
            .astype('string')
            .str.strip()
        )

        # Começa preservando os nulos da origem
        fase_tratada = pd.Series(
            pd.NA,
            index=df.index,
            dtype='Int64'
        )

        # ALFA -> 0
        mascara_alfa = fase_raw.str.upper().eq('ALFA')
        fase_tratada.loc[mascara_alfa] = 0

        # FASE 1, FASE 2 etc. -> extrai somente o número
        mascara_fase = fase_raw.str.upper().str.startswith('FASE', na=False)

        numeros = (
            fase_raw.loc[mascara_fase]
            .str.extract(r'(\d+)', expand=False)
        )

        fase_tratada.loc[mascara_fase] = pd.to_numeric(
            numeros,
            errors='coerce'
        ).astype('Int64')

        temp_passos_df['Fase'] = fase_tratada


    elif year == 2024:
        # Regras:
        # ALFA -> 0
        # 1A   -> 1
        # 2H   -> 2
        # 9    -> 9
        # nulo -> nulo

        fase_raw = (
            df['Fase']
            .astype('string')
            .str.strip()
            .str.upper()
        )

        # Extrai somente os números
        fase_tratada = fase_raw.str.extract(
            r'(\d+)',
            expand=False
        )

        # ALFA = 0
        fase_tratada.loc[
            fase_raw.eq('ALFA')
        ] = '0'

        temp_passos_df['Fase'] = (
            pd.to_numeric(
                fase_tratada,
                errors='coerce'
            )
            .astype('Int64')
        )


    # --- Turma (caracter) ---
    if year == 2020:
        # Ex.: "2H" -> "H"
        turma_raw = df.get(
            'FASE_TURMA_2020',
            pd.Series(index=df.index, dtype=object)
        ).astype('string').str.strip()

        temp_passos_df['Turma'] = (
            turma_raw
            .str.extract(r'^\s*\d*\s*([A-Za-z])', expand=False)
            .str.upper()
        )

    elif year == 2021:
        # Copia TURMA_2021
        temp_passos_df['Turma'] = (
            df.get(
                'TURMA_2021',
                pd.Series(index=df.index, dtype=object)
            )
            .astype('string')
            .str.strip()
            .replace('', pd.NA)
        )

    elif year == 2022:
        # Copia Turma sem alteração
        temp_passos_df['Turma'] = (
            df.get(
                'Turma',
                pd.Series(index=df.index, dtype=object)
            )
            .astype('string')
            .str.strip()
            .replace('', pd.NA)
        )

    elif year in [2023, 2024]:
        turma_raw = df.get(
            'Turma',
            pd.Series(index=df.index, dtype=object)
        ).astype('string').str.strip()

        # Caso especial:
        # "ALFA B - G2/G3" -> "B"
        turma_alfa = turma_raw.str.extract(
            r'(?i)\bALFA\s*([A-Za-z])',
            expand=False
        )

        # Casos normais:
        # "2H" -> "H"
        # "3A" -> "A"
        # "B"  -> "B"
        turma_normal = turma_raw.str.extract(
            r'^\s*\d*\s*([A-Za-z])',
            expand=False
        )

        temp_passos_df['Turma'] = (
            turma_alfa
            .fillna(turma_normal)
            .str.upper()
        )

    # --- Idade (Nr inteiro) ---
    idade_col = None
    if year == 2020:
        idade_col = 'IDADE_ALUNO_2020'
    elif year == 2022:
        idade_col = 'Idade 22'
    elif year in [2023, 2024]:
        idade_col = 'Idade'
    temp_passos_df['Idade'] = pd.to_numeric(df.get(idade_col, pd.Series(index=df.index, dtype=object)), errors='coerce').astype('Int64')

    # --- Ano_ingresso (Ano) ---
    ano_ingresso_col = 'Ano ingresso'
    temp_passos_df['Ano_ingresso'] = pd.to_numeric(df.get(ano_ingresso_col, pd.Series(index=df.index, dtype=object)), errors='coerce').astype('Int64')

    # --- Instituicao_ensino (caracter) ---
    inst_ensino_col = None
    if year == 2020:
        inst_ensino_col = 'INSTITUICAO_ENSINO_ALUNO_2020'
    elif year == 2021:
        inst_ensino_col = 'INSTITUICAO_ENSINO_ALUNO_2021'
    elif year in [2022, 2023, 2024]:
        inst_ensino_col = 'Instituição de ensino'
    temp_passos_df['Instituicao_ensino'] = df.get(inst_ensino_col, pd.Series(index=df.index, dtype=object)).astype(str).replace({'nan': pd.NA})

    # --- CG, CF, CT (decimal) ---
    temp_passos_df['CG'] = pd.to_numeric(df.get('Cg', pd.Series(index=df.index, dtype=object)), errors='coerce')
    temp_passos_df['CF'] = pd.to_numeric(df.get('Cf', pd.Series(index=df.index, dtype=object)), errors='coerce')
    temp_passos_df['CT'] = pd.to_numeric(df.get('Ct', pd.Series(index=df.index, dtype=object)), errors='coerce')

    # --- Nr_avaliacoes (Nr inteiro) ---
    nr_av_col = 'Nº Av'
    temp_passos_df['Nr_avaliacoes'] = pd.to_numeric(df.get(nr_av_col, pd.Series(index=df.index, dtype=object)), errors='coerce').astype('Int64')

    # --- Rec_psicologia (caracter) ---
    rec_psicologia_col = 'Rec Psicologia'
    temp_passos_df['Rec_psicologia'] = df.get(rec_psicologia_col, pd.Series(index=df.index, dtype=object)).astype(str).replace({'nan': pd.NA})

    # --- Indicado_bolsa (caracter) ---
    indicado_col = 'Indicado'
    temp_passos_df['Indicado_bolsa'] = df.get(indicado_col, pd.Series(index=df.index, dtype=object)).astype(str).replace({'nan': pd.NA})

    # --- Atingiu_PV (caracter) ---
    atingiu_pv_col = 'Atingiu PV'
    temp_passos_df['Atingiu_PV'] = df.get(atingiu_pv_col, pd.Series(index=df.index, dtype=object)).astype(str).replace({'nan': pd.NA})

    # --- Fase_ideal (Nr inteiro) ---
    if year == 2021:
        fase_ideal_series_raw = df.get('NIVEL_IDEAL_2021', pd.Series(index=df.index, dtype=object)).astype(str)
        fase_ideal_series = fase_ideal_series_raw.str.extract(r'(\d+)', expand=False)
        # Removed .fillna('0') to preserve actual NaNs
        fase_ideal_series[fase_ideal_series_raw.str.contains('ALFA', na=False, case=False)] = '0'
        temp_passos_df['Fase_ideal'] = pd.to_numeric(fase_ideal_series, errors='coerce').astype('Int64')
    elif year in [2022, 2023, 2024]:
        fase_ideal_col_name = 'Fase Ideal' if 'Fase Ideal' in df.columns else 'Fase ideal'
        fase_ideal_series_raw = df.get(fase_ideal_col_name, pd.Series(index=df.index, dtype=object)).astype(str)
        fase_ideal_series = fase_ideal_series_raw.str.extract(r'(\d+)', expand=False)
        # Removed .fillna('0') to preserve actual NaNs
        fase_ideal_series[fase_ideal_series_raw.str.contains('ALFA', na=False, case=False)] = '0'
        temp_passos_df['Fase_ideal'] = pd.to_numeric(fase_ideal_series, errors='coerce').astype('Int64')
    else: # 2020 has no direct Fase_ideal
        temp_passos_df['Fase_ideal'] = pd.NA

    # --- Desafagem (Nr inteiro) ---
    desafagem_col = None
    if year == 2021:
        desafagem_col = 'DEFASAGEM_2021'
    elif year == 2022:
        desafagem_col = 'Defas'
    elif year in [2023, 2024]:
        desafagem_col = 'Defasagem'
    temp_passos_df['Desafagem'] = pd.to_numeric(df.get(desafagem_col, pd.Series(index=df.index, dtype=object)), errors='coerce').astype('Int64')

    # --- Escola (caracter) ---
    escola_col = 'Escola'
    temp_passos_df['Escola'] = df.get(escola_col, pd.Series(index=df.index, dtype=object)).astype(str).replace({'nan': pd.NA})

    # --- Status (caracter) ---
    status_col = 'Ativo/ Inativo'
    temp_passos_df['Status'] = df.get(status_col, pd.Series(index=df.index, dtype=object)).astype(str).replace({'nan': pd.NA})

    # Ensure all target columns exist, filling with NA if they were not populated for a specific year
    target_columns = ['RA', 'Ano', 'INDE', 'Fase', 'Turma', 'Idade', 'Ano_ingresso', 'Instituicao_ensino',
                      'CG', 'CF', 'CT', 'Nr_avaliacoes', 'Rec_psicologia', 'Indicado_bolsa',
                      'Atingiu_PV', 'Fase_ideal', 'Desafagem', 'Escola', 'Status']
    for col in target_columns:
        if col not in temp_passos_df.columns:
            temp_passos_df[col] = pd.NA

    # Reorder columns to match the requested order
    temp_passos_df = temp_passos_df[target_columns]

    return temp_passos_df

# Process each year's DataFrame
aluno_passos_2020 = process_passos_data(df_passos_2020.copy(), 2020)
aluno_passos_2021 = process_passos_data(df_passos_2021.copy(), 2021)
aluno_passos_2022 = process_passos_data(df_passos_2022.copy(), 2022)
aluno_passos_2023 = process_passos_data(df_passos_2023.copy(), 2023)
aluno_passos_2024 = process_passos_data(df_passos_2024.copy(), 2024)

# Concatenate all yearly DataFrames into the final ALUNO_PASSOS DataFrame
ALUNO_PASSOS = pd.concat([aluno_passos_2020, aluno_passos_2021, aluno_passos_2022, aluno_passos_2023, aluno_passos_2024], ignore_index=True)

# Display the first few rows of the new DataFrame
display(ALUNO_PASSOS.head())

/tmp/ipykernel_5282/1379964821.py:313: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ALUNO_PASSOS = pd.concat([aluno_passos_2020, aluno_passos_2021, aluno_passos_2022, aluno_passos_2023, aluno_passos_2024], ignore_index=True)

,RA,Ano,INDE,Fase,Turma,Idade,Ano_ingresso,Instituicao_ensino,CG,CF,CT,Nr_avaliacoes,Rec_psicologia,Indicado_bolsa,Atingiu_PV,Fase_ideal,Desafagem,Escola,Status
0,1,2020,"7,884",2,H,11,<NA>,Escola Pública,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN
1,2,2020,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN
2,3,2020,"7,856",3,H,12,<NA>,Escola Pública,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN
3,4,2020,"5,076",1,D,10,<NA>,Escola Pública,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN
4,5,2020,"8,077",2,M,10,<NA>,Escola Pública,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN

In [44]:
ALUNO_PASSOS.loc[ALUNO_PASSOS['RA'] == 480]

,RA,Ano,INDE,Fase,Turma,Idade,Ano_ingresso,Instituicao_ensino,CG,CF,CT,Nr_avaliacoes,Rec_psicologia,Indicado_bolsa,Atingiu_PV,Fase_ideal,Desafagem,Escola,Status
479,480,2020,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN
1828,480,2021,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN
3177,480,2022,"7,502",1,A,10,2021,Escola Pública,"309,000","81,000","6,000",3,Não atendido,Sim,Sim,2,-1,NaN,NaN
3804,480,2023,"8,226",1,B,11,2021,Pública,NaN,NaN,NaN,3,NaN,NaN,NaN,2,-1,NaN,NaN
4978,480,2024,"7,260",2,C,12,2021,Pública,NaN,NaN,NaN,3,NaN,NaN,NaN,2,0,EE Alexandre Rodrigues Nogueira,Cursando

### Alterando a fase 9 para 8

In [45]:
ALUNO_PASSOS.loc[
    ALUNO_PASSOS['Fase'] == 9,
    'Fase'
] = 8

### Preenchendo os INDE faltantes

In [46]:
# ============================================================
# PREENCHER INDE AUSENTE A PARTIR DAS MÉTRICAS
# Chave: RA + Ano
# ============================================================

# Garantir que INDE vazio seja tratado como nulo
ALUNO_PASSOS['INDE'] = pd.to_numeric(
    ALUNO_PASSOS['INDE'],
    errors='coerce'
)

# ------------------------------------------------------------
# Transformar ALUNO_METRICA:
# uma linha por RA/Ano e uma coluna para cada métrica
# ------------------------------------------------------------

metricas_inde = (
    ALUNO_METRICA[
        ALUNO_METRICA['Metrica'].isin(
            ['IAN', 'IDA', 'IEG', 'IAA', 'IPS', 'IPP', 'IPV']
        )
    ]
    .pivot_table(
        index=['RA', 'Ano'],
        columns='Metrica',
        values='Nota',
        aggfunc='first'
    )
    .reset_index()
)

# ------------------------------------------------------------
# Criar base auxiliar mantendo o índice da ALUNO_PASSOS
# ------------------------------------------------------------

base_calculo = ALUNO_PASSOS[
    ['RA', 'Ano', 'Fase', 'INDE']
].copy()

base_calculo['_indice'] = base_calculo.index

base_calculo = base_calculo.merge(
    metricas_inde,
    on=['RA', 'Ano'],
    how='left'
)

# Coluna para armazenar somente os INDEs que serão calculados
base_calculo['INDE_calculado'] = np.nan


# ============================================================
# FASES 0 A 7
#
# INDE =
# IAN * 0.1 +
# IDA * 0.2 +
# IEG * 0.2 +
# IAA * 0.1 +
# IPS * 0.1 +
# IPP * 0.1 +
# IPV * 0.2
# ============================================================

metricas_fase_0_7 = [
    'IAN',
    'IDA',
    'IEG',
    'IAA',
    'IPS',
    'IPP',
    'IPV'
]

tem_metricas_0_7 = (
    base_calculo[metricas_fase_0_7]
    .notna()
    .all(axis=1)
)

mask_0_7 = (
    base_calculo['INDE'].isna()
    & base_calculo['Fase'].notna()
    & base_calculo['Fase'].between(0, 7)
    & tem_metricas_0_7
)

base_calculo.loc[mask_0_7, 'INDE_calculado'] = (
    base_calculo.loc[mask_0_7, 'IAN'] * 0.1
    + base_calculo.loc[mask_0_7, 'IDA'] * 0.2
    + base_calculo.loc[mask_0_7, 'IEG'] * 0.2
    + base_calculo.loc[mask_0_7, 'IAA'] * 0.1
    + base_calculo.loc[mask_0_7, 'IPS'] * 0.1
    + base_calculo.loc[mask_0_7, 'IPP'] * 0.1
    + base_calculo.loc[mask_0_7, 'IPV'] * 0.2
)


# ============================================================
# FASE 8
#
# INDE =
# IAN * 0.1 +
# IDA * 0.4 +
# IEG * 0.2 +
# IAA * 0.1 +
# IPS * 0.2
# ============================================================

metricas_fase_8 = [
    'IAN',
    'IDA',
    'IEG',
    'IAA',
    'IPS'
]

tem_metricas_8 = (
    base_calculo[metricas_fase_8]
    .notna()
    .all(axis=1)
)

mask_8 = (
    base_calculo['INDE'].isna()
    & base_calculo['Fase'].eq(8)
    & tem_metricas_8
)

base_calculo.loc[mask_8, 'INDE_calculado'] = (
    base_calculo.loc[mask_8, 'IAN'] * 0.1
    + base_calculo.loc[mask_8, 'IDA'] * 0.4
    + base_calculo.loc[mask_8, 'IEG'] * 0.2
    + base_calculo.loc[mask_8, 'IAA'] * 0.1
    + base_calculo.loc[mask_8, 'IPS'] * 0.2
)


# ============================================================
# LEVAR O INDE CALCULADO PARA ALUNO_PASSOS
# ============================================================

inde_calculado = (
    base_calculo
    .set_index('_indice')['INDE_calculado']
)

mask_preencher = (
    ALUNO_PASSOS['INDE'].isna()
    & inde_calculado.notna()
)

ALUNO_PASSOS.loc[
    mask_preencher,
    'INDE'
] = inde_calculado.loc[mask_preencher]

# Arredondar para 3 casas decimais
ALUNO_PASSOS['INDE'] = ALUNO_PASSOS['INDE'].round(3)

In [47]:
print(
    "Quantidade de INDE calculados:",
    mask_preencher.sum()
)

print(
    "Quantidade de INDE ainda nulos:",
    ALUNO_PASSOS['INDE'].isna().sum()
)

Quantidade de INDE calculados: 2
Quantidade de INDE ainda nulos: 1470

In [48]:
display(
    ALUNO_PASSOS.loc[
        mask_preencher,
        ['RA', 'Ano', 'Fase', 'INDE']
    ].head(20)
)

       RA   Ano  Fase  INDE
1419   71  2021     0 2,460
1854  506  2021     0 3,060

# EXPORTANDO OS DATAFRAMES

In [49]:
# Exportar o DataFrame ALUNO_PASSOS para um arquivo Excel
ALUNO_PASSOS.to_excel('ALUNO_PASSOS.xlsx', index=False)
print("DataFrame ALUNO_PASSOS exportado com sucesso para 'ALUNO_PASSOS.xlsx'")

ALUNO.to_excel('ALUNO.xlsx', index=False)
print("DataFrame ALUNO exportado com sucesso para 'ALUNO.xlsx'")

ALUNO_PEDRA.to_excel('ALUNO_PEDRA.xlsx', index=False)
print("DataFrame ALUNO_PEDRA exportado com sucesso para 'ALUNO_PEDRA.xlsx'")

ALUNO_AVALIACAO.to_excel('ALUNO_AVALIACAO.xlsx', index=False)
print("DataFrame ALUNO_AVALIACAO exportado com sucesso para 'ALUNO_AVALIACAO.xlsx'")

ALUNO_METRICA.to_excel('ALUNO_METRICA.xlsx', index=False)
print("DataFrame ALUNO_METRICA exportado com sucesso para 'ALUNO_METRICA.xlsx'")

ALUNO_MATERIA.to_excel('ALUNO_MATERIA.xlsx', index=False)
print("DataFrame ALUNO_MATERIA exportado com sucesso para 'ALUNO_MATERIA.xlsx'")

DataFrame ALUNO_PASSOS exportado com sucesso para 'ALUNO_PASSOS.xlsx'
DataFrame ALUNO exportado com sucesso para 'ALUNO.xlsx'
DataFrame ALUNO_PEDRA exportado com sucesso para 'ALUNO_PEDRA.xlsx'
DataFrame ALUNO_AVALIACAO exportado com sucesso para 'ALUNO_AVALIACAO.xlsx'
DataFrame ALUNO_METRICA exportado com sucesso para 'ALUNO_METRICA.xlsx'
DataFrame ALUNO_MATERIA exportado com sucesso para 'ALUNO_MATERIA.xlsx'

In [50]:

from google.colab import files

files.download('ALUNO_PASSOS.xlsx')
files.download('ALUNO.xlsx')
files.download('ALUNO_PEDRA.xlsx')
files.download('ALUNO_AVALIACAO.xlsx')
files.download('ALUNO_METRICA.xlsx')
files.download('ALUNO_MATERIA.xlsx')

# *** Perguntas para ser respondidas na análise ***

# 1. Adequação do nível (IAN)
    IAN = 10  -> Em fase
    IAN = 5   -> Moderada
    IAN = 2,5 -> Severa
Qual é o perfil geral de defasagem dos alunos (IAN) e como ele evolui ao
longo do ano?
(Ex.: quantos alunos estão moderadamente ou severamente defasados?)

** Resolução no Power BI

# 2. Desempenho acadêmico (IDA)
    Fórmula: IDA = (Nota Matemática + Nota Português + Nota Inglês) / 3
O desempenho acadêmico médio (IDA) está melhorando, estagnado ou
caindo ao longo das fases e anos?

** Resolução no Power BI

 # 3. Engajamento nas atividades (IEG)
    IEG = Soma das pontuações das tarefas realizadas e registradas / Número de tarefas
O grau de engajamento dos alunos (IEG) tem relação direta com seus
indicadores de desempenho (IDA) e do ponto de virada (IPV)?

** Resolução no Power BI

 # 4. Autoavaliação (IAA)
    IAA = Soma das pontuações das respostas do estudante / Número total de perguntas
As percepções dos alunos sobre si mesmos (IAA) são coerentes com seu
desempenho real (IDA) e engajamento (IEG)?

** Resolução no Power BI

# 5. Aspectos psicossociais (IPS)
    IPS = Soma das pontuações dos avaliadores / Número de avaliadores
Há padrões psicossociais (IPS) que antecedem quedas de desempenho
acadêmico ou de engajamento?

** Resolução no Power BI

# 6. Aspectos psicopedagógicos (IPP)
    IPP = Soma das avaliações sobre aspectos pedagógicos / Número de avaliações
As avaliações psicopedagógicas (IPP) confirmam ou contradizem a
defasagem identificada pelo IAN?

** Resolução no Power BI

# 7. Ponto de virada (IPV)
    IPV = Análises longitudinais de progresso acadêmico, engajamento e desenvolvimento emocional
Quais comportamentos - acadêmicos, emocionais ou de engajamento -
mais influenciam o IPV ao longo do tempo?

** Resolução no Power BI

# 8. Multidimensionalidade dos indicadores
    INDE fases 0 à 7 = IAN × 0,1 + IDA × 0,2 + IEG × 0,2 + IAA × 0,1 + IPS × 0,1 + IPP × 0,1 + IPV × 0,2
    INDE fase 8 = INDE = IAN × 0,1 + IDA × 0,4 + IEG × 0,2 + IAA × 0,1 + IPS × 0,2    
Quais combinações de indicadores (IDA + IEG + IPS + IPP) elevam mais
a nota global do aluno (INDE)?

** Resolução no Power BI